// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrontendClient is the client API for Frontend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendClient interface {
	Increment(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error)
}

type frontendClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendClient(cc grpc.ClientConnInterface) FrontendClient {
	return &frontendClient{cc}
}

func (c *frontendClient) Increment(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error) {
	out := new(IncResponse)
	err := c.cc.Invoke(ctx, "/pb.Frontend/increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontendServer is the server API for Frontend service.
// All implementations must embed UnimplementedFrontendServer
// for forward compatibility
type FrontendServer interface {
	Increment(context.Context, *IncRequest) (*IncResponse, error)
	mustEmbedUnimplementedFrontendServer()
}

// UnimplementedFrontendServer must be embedded to have forward compatible implementations.
type UnimplementedFrontendServer struct {
}

func (UnimplementedFrontendServer) Increment(context.Context, *IncRequest) (*IncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedFrontendServer) mustEmbedUnimplementedFrontendServer() {}

// UnsafeFrontendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServer will
// result in compilation errors.
type UnsafeFrontendServer interface {
	mustEmbedUnimplementedFrontendServer()
}

func RegisterFrontendServer(s grpc.ServiceRegistrar, srv FrontendServer) {
	s.RegisterService(&Frontend_ServiceDesc, srv)
}

func _Frontend_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Frontend/increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServer).Increment(ctx, req.(*IncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Frontend_ServiceDesc is the grpc.ServiceDesc for Frontend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Frontend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Frontend",
	HandlerType: (*FrontendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "increment",
			Handler:    _Frontend_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/pb.proto",
}

// ReplicaManagerClient is the client API for ReplicaManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicaManagerClient interface {
	Increment(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error)
}

type replicaManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaManagerClient(cc grpc.ClientConnInterface) ReplicaManagerClient {
	return &replicaManagerClient{cc}
}

func (c *replicaManagerClient) Increment(ctx context.Context, in *IncRequest, opts ...grpc.CallOption) (*IncResponse, error) {
	out := new(IncResponse)
	err := c.cc.Invoke(ctx, "/pb.ReplicaManager/increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaManagerServer is the server API for ReplicaManager service.
// All implementations must embed UnimplementedReplicaManagerServer
// for forward compatibility
type ReplicaManagerServer interface {
	Increment(context.Context, *IncRequest) (*IncResponse, error)
	mustEmbedUnimplementedReplicaManagerServer()
}

// UnimplementedReplicaManagerServer must be embedded to have forward compatible implementations.
type UnimplementedReplicaManagerServer struct {
}

func (UnimplementedReplicaManagerServer) Increment(context.Context, *IncRequest) (*IncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedReplicaManagerServer) mustEmbedUnimplementedReplicaManagerServer() {}

// UnsafeReplicaManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaManagerServer will
// result in compilation errors.
type UnsafeReplicaManagerServer interface {
	mustEmbedUnimplementedReplicaManagerServer()
}

func RegisterReplicaManagerServer(s grpc.ServiceRegistrar, srv ReplicaManagerServer) {
	s.RegisterService(&ReplicaManager_ServiceDesc, srv)
}

func _ReplicaManager_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaManagerServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReplicaManager/increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaManagerServer).Increment(ctx, req.(*IncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaManager_ServiceDesc is the grpc.ServiceDesc for ReplicaManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ReplicaManager",
	HandlerType: (*ReplicaManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "increment",
			Handler:    _ReplicaManager_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/pb.proto",
}
